import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-gradient-to-b from-[#f9e9f2] to-[#d1eeee]">
      <body className="w-[calc(100vw_-_20px)] mx-auto">{children}</body>
    </html>
  );
}
