import "./globals.css";
import localFont from "next/font/local";
import Navbar from "./ui/navbar";

const proxima = localFont({
  src: [
    {
      path: "./static-fonts/ProximaSoft-Thin.woff2",
      weight: "100",
      style: "thin",
    },
    {
      path: "./static-fonts/ProximaSoft-Medium.woff2",
      weight: "400",
      style: "regular",
    },
    {
      path: "./static-fonts/ProximaSoft-Regular.woff2",
      weight: "500",
      style: "bold",
    },
    {
      path: "./static-fonts/ProximaSoft-Bold.woff2",
      weight: "700",
      style: "bold",
    },
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-gradient-to-b from-[#f9e9f2] to-[#d1eeee]">
      <body className={proxima.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
